---
title: "6372Project2"
author: "Shon Mohsin, Daniel Serna, William Trevino"
date: "November 3, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraryImports}
if(!require(tidyverse)) install.packages("tidyverse")
if(!require(caret)) install.packages("caret")
if(!require(knitr)) install.packages("knitr")
```

```{r addUtilityFunctions}
panel.hist <- function(x, ...)
{
    usr <- par("usr"); on.exit(par(usr))
    par(usr = c(usr[1:2], 0, 1.5) )
    h <- hist(x, plot = FALSE)
    breaks <- h$breaks; nB <- length(breaks)
    y <- h$counts; y <- y/max(y)
    rect(breaks[-nB], 0, breaks[-1], y, col = "cyan", ...)
}

addConstantForLogTransform <- function(x)
{
  returnValue = x + (1 - min(x))
}
```

```{r importData}
trainData <- read.csv("project2Data.csv")
```

```{r dataTransformations}
trainData$time_remaining_period <- trainData$seconds_remaining +(60*trainData$minutes_remaining) 
trainData$game_time <- (12*60 - trainData$time_remaining_period) + ((trainData$period - 1)*12*60)
```

```{r outlierAnalysis}
pairs(~shot_made_flag+action_type+combined_shot_type+lat+lon+loc_x+loc_y,data=trainData,main="Simple Scatterplot Matrix", diag.panel=panel.hist)

pairs(~time_remaining_period+game_time+playoffs+season+shot_distance+shot_type,data=trainData,main="Simple Scatterplot Matrix", diag.panel=panel.hist)

pairs(~shot_zone_basic+shot_zone_area+shot_zone_range+game_date+opponent+attendance+arena_temp+avgnoisedb,data=trainData,main="Simple Scatterplot Matrix", diag.panel=panel.hist)

```

```{r logTransformations}
trainData$log_lat = log(trainData$lat)
#we have 0s in the shot_distance field, so we need to add a small number so we can take the log transform.
trainData$log_shot_distance = log(trainData$shot_distance + 0.001)
#we have negative values in the following fields, so we need to add a constant so we can take the log tranform.
trainData$log_loc_y = log(addConstantForLogTransform(trainData$loc_y))

#the above log transformations don't seem to help much at all.
pairs(~log_shot_distance+log_lat+log_loc_y,data=trainData,main="Simple Scatterplot Matrix", diag.panel=panel.hist)
```

```{r varianceInflationFactor}
trainData$team_name <- NULL #this is always Lakers
trainData$team_id <- NULL #this is always Lakers
trainData$game_date <- NULL
trainData$matchup <- NULL
trainData$recId <- NULL
trainData$game_event_id <- NULL
trainData$game_id <- NULL
trainData$shot_id <- NULL
trainData$combined_shot_type <- NULL
trainData$shot_zone_basic <- NULL
trainData$loc_x <- NULL
trainData$loc_y <- NULL
trainData$shot_zone_range <- NULL
trainData$log_lat <-NULL
trainData$log_loc_y <-NULL
trainData$log_shot_distance <-NULL
trainData$minutes_remaining <-NULL
trainData$seconds_remaining <-NULL
trainData$period <-NULL


set.seed(123)
trainData.samples <- trainData$shot_made_flag %>%
  createDataPartition(p = 0.8, list = FALSE)
train.data  <- trainData[trainData.samples, ]
test.data <- trainData[-trainData.samples, ]


# Build the model
model1 <- lm(shot_made_flag~., data = train.data)
# Make predictions
predictions <- model1 %>% predict(test.data)
# Model performance
data.frame(
  RMSE = RMSE(predictions, test.data$shot_made_flag),
  R2 = R2(predictions, test.data$shot_made_flag)
)

# Determine multicollinearity
car::vif(model1)

# Write variable VIF to csv file for analysis
datavif <- car::vif(model1)
write.csv(datavif, "datavif.csv")

#after successful vif run, we removed the following variable
trainData$shot_zone_area <- NULL

set.seed(123)
trainData.samples <- trainData$shot_made_flag %>%
  createDataPartition(p = 0.8, list = FALSE)
train.data  <- trainData[trainData.samples, ]
test.data <- trainData[-trainData.samples, ]


# Build the model
model1 <- lm(shot_made_flag ~., data = train.data)
# Make predictions
predictions <- model1 %>% predict(test.data)
# Model performance
data.frame(
  RMSE = RMSE(predictions, test.data$shot_made_flag),
  R2 = R2(predictions, test.data$shot_made_flag)
)

# Determine multicollinearity
car::vif(model1)

# Write variable VIF to csv file for analysis
datavif <- car::vif(model1)
write.csv(datavif, "datavif.csv")

trainData2 <- trainData
trainData2$action_type <- NULL

set.seed(123)
trainData2.samples <- trainData2$shot_made_flag %>%
  createDataPartition(p = 0.8, list = FALSE)
train2.data  <- trainData2[trainData2.samples, ]
test2.data <- trainData2[-trainData2.samples, ]


# Build the model
model2 <- lm(shot_made_flag ~., data = train2.data)
# Make predictions
predictions2 <- model2 %>% predict(test2.data)
# Model performance
data.frame(
  RMSE = RMSE(predictions2, test2.data$shot_made_flag),
  R2 = R2(predictions2, test2.data$shot_made_flag)
)

# Determine multicollinearity
car::vif(model2)

# Write variable VIF to csv file for analysis
datavif2 <- car::vif(model2)
write.csv(datavif2, "datavif2.csv")
```

```{r exportData}
write.csv(trainData, "trainDataClean.csv")
```